version: '4'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: pgsql

  # app:
  #    container_name: abdim-api
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    depends_on:
  #      - pgsql
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - .:/usr/src/app

volumes:
  pg-data: